name: Build
on: [push, pull_request]

jobs:

  build-linux:
    name: Compile binaries for Linux
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.0-dev

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    #Cargo build release
    - name: Compile
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    
    # Strip and compress with UPX
    - name: Compress
      run: strip target/release/discogstaggerrs
    - uses: gacts/upx@master
      with:
        file: 'target/release/discogstaggerrs'
        upx_args: '-9'
    
    #Upload
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: discogstagger-linux
        path: target/release/discogstaggerrs
