name: Build
on: [push, pull_request]

jobs:

  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.0-dev

    # Get repo
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    # Cargo build release
    - name: Compile
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    
    # Strip and compress with UPX
    - uses: joshuarli/strip-upx-action@master
      with:
        infile: 'target/release/discogstaggerrs'
        strip_args: '--strip-all'
        upx_args: '-9'
    
    # Upload
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: discogstagger-linux
        path: target/release/discogstaggerrs

  build-mac:
    name: Mac
    runs-on: macos-latest

    steps:

    # Get repo
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    # Install cargo bundler
    - name: Install cargo-bundle
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-bundle
    
    # Cargo build release
    - name: Compile
      uses: actions-rs/cargo@v1
      with:
        command: bundle
        args: --release
    
    # Strip and compress with UPX
    - name: Compress
      run: |
        brew install upx
        strip target/release/bundle/osx/DiscogsTagger.app/Contents/MacOS/discogstaggerrs
        upx -9 target/release/bundle/osx/DiscogsTagger.app/Contents/MacOS/discogstaggerrs

    # Upload
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: discogstagger-mac
        path: target/release/bundle/osx/DiscogsTagger.app

  build-win:
    name: Windows
    runs-on: windows-latest

    steps:

    # Get repo
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    # Cargo build release
    - name: Compile
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    
    # Compress with UPX
    - name: Compress
      run: |
        choco install upx
        upx -9 target\release\discogstaggerrs.exe
    
    # Upload
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: discogstagger-win
        path: target\release\discogstaggerrs.exe
